#ifndef KOYOTECOIN_CHAINPARAMSSEEDS_H
#define KOYOTECOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the koyotecoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x95,0x38,0x66,0x03,0x1f,0xae,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x95,0x38,0x66,0x03,0x46,0xbe,
};
#endif // KOYOTECOIN_CHAINPARAMSSEEDS_H